# Generated by Django 6.0.2 on 2026-02-20 21:16

import glob
import os

from django.db import migrations

# Map park names to image file slugs where they differ
PARK_TO_SLUG = {
    "Presidio": "presidio_of_san_francisco",
    "India Basin Shoreline Park": "india_basin",
    "Justin Herman Plaza (Embarcadero Plaza)": "justin_herman_plaza",
    "Mountain Lake Park": "mountain_lake",
    "Tank Hill Park": "tank_hill",
    "Mount Davidson Park": "mount_davidson",
    "Crocker Amazon Playground": "crocker-amazon_playground",
    "Potrero Hill Recreation Center": "potrero_hill",
    "Noe Valley Town Square": "noe_valley",
    "Miraloma Playground": "miraloma_park_san_francisco",
    "Visitacion Valley Greenway": "visitacion_valley_san_francisco",
    "Civic Center Plaza": "civic_center_san_francisco",
    "John McLaren Playground": "john_mclaren_park",
    "McLaren Park": "mclaren_park",
    "Balboa Park": "balboa_park_san_francisco",
}


def _slugify(name):
    """Same slugification used by fetch_park_images.py title_to_filename."""
    import re
    name = name.split("(")[0].strip()
    name = re.sub(r"[^\w\s-]", "", name)
    name = re.sub(r"[\s]+", "_", name).strip("_").lower()
    return name


def populate_images(apps, schema_editor):
    Park = apps.get_model("parks", "Park")
    imgs_dir = os.path.join(
        os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
        "imgs",
    )
    for park in Park.objects.all():
        slug = PARK_TO_SLUG.get(park.name, _slugify(park.name))
        matches = glob.glob(os.path.join(imgs_dir, slug + ".*"))
        if matches:
            park.image = os.path.basename(matches[0])
            park.save(update_fields=["image"])


def clear_images(apps, schema_editor):
    Park = apps.get_model("parks", "Park")
    Park.objects.update(image="")


class Migration(migrations.Migration):

    dependencies = [
        ("parks", "0002_park_image"),
    ]

    operations = [
        migrations.RunPython(populate_images, clear_images),
    ]
